### PR TITLE
Pwsh compatible

### PR DESCRIPTION
**Pull request by copdips**
Hello,

This PR makes the module compatible to pwsh v6 and v7.
(with some minor code format changes done by the editor automatically.)

Tested powershell versions : 
- powershell v5.1
- pwsh v6.2.2
- pwsh v7.0.0-preview.3

Only one test failed : 

```
[-] Can decrypt vault unicode_1.1 with password @(195, 162, 194, 157, 197, 146, 195, 162, 197, 190) 255ms
        ArgumentException: HMAC verification failed, was the wrong password entered?
```

### CODE REVIEW

**Comment by copdips** [comment]
looks that the test `Can decrypt vault unicode_1.1 with password @(195, 162, 194, 157, 197, 146, 195, 162, 197, 190)` succeeded on AppVeyor server, although it failed on my local windows 10.

**Comment by copdips** [comment]
@jborean93 

Could you please check this PR ?

**Comment by jborean93** [comment]
Hi sorry it might take some time before I get to this sorry. I’m at a conference this week and then going on holidays after that. If you are feeling up to it would be nice to optional remove the Windows PInvoke stuff to favour .net if possible. This would make this compatible across on Linux and not just Windows. We would still need to fall back to the PInvoke code though for older PowerShell versions.

**Comment by copdips** [comment]
To be honest, I know nearly nothing on dotnet, but when I have time, I will make a try.

**Comment by jborean93** [comment]
Sorry for the delay on this one, have just gotten back from holidays. The changes seem good to me. I'll merge this in and have a look at trying to get this working on Core for Linux before the next release.

**Pull request merged**
